In [2]:
import numpy as np
a = np.array([1,2,3])
np.repeat(a,2,axis=None)

array([1, 1, 2, 2, 3, 3])

In [3]:
import numpy as np
a = np.array([1,2])
np.repeat(a,[2,3],axis=0)

array([1, 1, 2, 2, 2])

In [5]:
import numpy as np
x = np.array([[1,2],[3,4]])
np.repeat(x, [1, 2], axis=0)


array([[1, 2],
       [3, 4],
       [3, 4]])

In [10]:
import numpy as np
x = np.array([[1,2],[3,4]])
np.repeat(x, 3, axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [11]:
import numpy as np
a = np.array([10, 5, 15, 20])
indices = np.argsort(a)
print("Indices that would sort the array:", indices)
sorted_a = a[indices]
print("Sorted array:", sorted_a)

Indices that would sort the array: [1 0 2 3]
Sorted array: [ 5 10 15 20]
